"""ReadedBook BookOwner tables created

Revision ID: 08bbc55c6650
Revises: ed9dba758631
Create Date: 2025-07-15 21:43:29.603364

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '08bbc55c6650'
down_revision: Union[str, Sequence[str], None] = 'ed9dba758631'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readed_books', sa.Column('start', sa.String(), nullable=True))
    op.add_column('readed_books', sa.Column('end', sa.String(), nullable=True))
    op.drop_column('readed_books', 'date_read')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('readed_books', sa.Column('date_read', sa.VARCHAR(), nullable=True))
    op.drop_column('readed_books', 'end')
    op.drop_column('readed_books', 'start')
    # ### end Alembic commands ###
