"""create new columns date_joined and birth_date

Revision ID: 2a0f95b46558
Revises: d286512b8fe0
Create Date: 2025-07-10 22:22:19.269460

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2a0f95b46558'
down_revision: Union[str, Sequence[str], None] = 'd286512b8fe0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('date_joined', sa.String(length=255), nullable=False))
    op.add_column('users', sa.Column('birth_date', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'date_joined')
    # ### end Alembic commands ###
