"""date_added column added to books table

Revision ID: 7fe97b5021bc
Revises: a8a67340d426
Create Date: 2025-07-25 13:33:32.757763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7fe97b5021bc'
down_revision: Union[str, Sequence[str], None] = 'a8a67340d426'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rented_books_id'), table_name='rented_books')
    op.drop_table('rented_books')
    op.add_column('books', sa.Column('date_added', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'date_added')
    op.create_table('rented_books',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('date_added', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rented_books_id'), 'rented_books', ['id'], unique=False)
    # ### end Alembic commands ###
