"""BookOwner to RentedBook

Revision ID: a8a67340d426
Revises: 08bbc55c6650
Create Date: 2025-07-15 23:02:29.692674

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a8a67340d426'
down_revision: Union[str, Sequence[str], None] = '08bbc55c6650'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('rented_books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('owner_id', sa.Integer(), nullable=False),
    sa.Column('date_added', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rented_books_id'), 'rented_books', ['id'], unique=False)
    op.drop_index(op.f('ix_book_owners_id'), table_name='book_owners')
    op.drop_table('book_owners')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('book_owners',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('book_id', sa.INTEGER(), nullable=False),
    sa.Column('owner_id', sa.INTEGER(), nullable=False),
    sa.Column('date_added', sa.VARCHAR(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_book_owners_id'), 'book_owners', ['id'], unique=False)
    op.drop_index(op.f('ix_rented_books_id'), table_name='rented_books')
    op.drop_table('rented_books')
    # ### end Alembic commands ###
